version: '3.6'
services:
  postgres:
    image: postgres:11
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
    - '8080:8080'
    depends_on:
    - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: testsecret
      HASURA_GRAPHQL_AUTH_HOOK: http://auth:3000
      FILE_PROCESSOR_URL: http://backend:3000/uploadTrigger
      SEND_MESSAGE_URL: http://backend:3000/api/sms/send
  auth:
    image: httpsomkar/keycloak-hasura-connector:latest
    env_file:
      - "./auth_variables.env"
  backend:
    build: ./test_backend
    ports:
    - '3000:3000'

volumes:
  db_data:
